import { MyReviewItem } from "../_hooks/use-my-reviews";

export const myReviewMockData: MyReviewItem[] = [
  {
    breederId: "1",
    breederName: "냥 1번째",
    breederLevel: "elite",
    applicationDate: "2024. 01. 15.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "100프로 대면상담으로 이루어지는 곳 사장님의 철학이 묻어나고, 블로그글만 봐도 브리딩에 열정과 진심이 느껴져서 정말 추천하는 곳입니다. 하100 프로 대면상담으로 이루어지는 곳 사장님의 철학이 묻어나고, 블로그글만 봐도 브리딩에 열정과 진심이 느껴져서 정말 추천하는 곳입니다.",
    reviewDate: "2024. 01. 20.",
  },
  {
    breederId: "2",
    breederName: "멍 1번째",
    breederLevel: "new",
    applicationDate: "2024. 01. 18.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "브리더님과의 상담이 매우 친절하고 전문적이었습니다. 모든 질문에 대해 상세하게 답변해주셔서 입양에 대한 확신을 갖게 되었어요.",
    reviewDate: "2024. 01. 22.",
  },
  {
    breederId: "3",
    breederName: "냥 2번째",
    breederLevel: "elite",
    applicationDate: "2024. 02. 05.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양 후 아이가 건강하게 잘 자라고 있습니다. 브리더님의 세심한 케어 덕분에 안심하고 입양할 수 있었어요.",
    reviewDate: "2024. 02. 15.",
  },
  {
    breederId: "4",
    breederName: "멍 2번째",
    breederLevel: "new",
    applicationDate: "2024. 02. 10.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담 과정에서 브리더님의 진심이 느껴졌습니다. 입양 전 모든 정보를 투명하게 공유해주셔서 신뢰할 수 있었어요.",
    reviewDate: "2024. 02. 12.",
  },
  {
    breederId: "5",
    breederName: "냥 3번째",
    breederLevel: "elite",
    applicationDate: "2024. 02. 20.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양 후 지금까지 아이가 건강하게 잘 지내고 있습니다. 브리더님의 철저한 건강 관리 덕분입니다.",
    reviewDate: "2024. 03. 01.",
  },
  {
    breederId: "6",
    breederName: "멍 3번째",
    breederLevel: "new",
    applicationDate: "2024. 03. 05.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담 시 브리더님의 전문성과 열정이 느껴졌습니다. 입양 후에도 지속적인 지원을 해주셔서 감사합니다.",
    reviewDate: "2024. 03. 08.",
  },
  {
    breederId: "7",
    breederName: "냥 4번째",
    breederLevel: "elite",
    applicationDate: "2024. 03. 12.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양한 지 한 달이 지났는데 아이가 정말 건강하고 활발합니다. 브리더님의 케어가 탁월했습니다.",
    reviewDate: "2024. 03. 25.",
  },
  {
    breederId: "8",
    breederName: "멍 4번째",
    breederLevel: "new",
    applicationDate: "2024. 03. 18.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담에서 모든 궁금증이 해결되었습니다. 브리더님의 친절한 설명 덕분에 입양을 결정할 수 있었어요.",
    reviewDate: "2024. 03. 20.",
  },
  {
    breederId: "9",
    breederName: "냥 5번째",
    breederLevel: "elite",
    applicationDate: "2024. 04. 01.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양 후 아이가 가족과 잘 어울려 지내고 있습니다. 브리더님의 사회화 교육이 잘 되어있었어요.",
    reviewDate: "2024. 04. 10.",
  },
  {
    breederId: "10",
    breederName: "멍 5번째",
    breederLevel: "new",
    applicationDate: "2024. 04. 08.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담 시 브리더님의 진심이 전해졌습니다. 입양에 대한 모든 정보를 투명하게 공유해주셔서 신뢰할 수 있었어요.",
    reviewDate: "2024. 04. 12.",
  },
  {
    breederId: "11",
    breederName: "냥 6번째",
    breederLevel: "elite",
    applicationDate: "2024. 04. 15.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양 후 아이가 건강하게 잘 자라고 있습니다. 브리더님의 세심한 케어가 느껴져요.",
    reviewDate: "2024. 04. 22.",
  },
  {
    breederId: "12",
    breederName: "멍 6번째",
    breederLevel: "new",
    applicationDate: "2024. 04. 20.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담 과정이 매우 체계적이고 전문적이었습니다. 브리더님의 노하우가 느껴졌어요.",
    reviewDate: "2024. 04. 25.",
  },
  {
    breederId: "13",
    breederName: "냥 7번째",
    breederLevel: "elite",
    applicationDate: "2024. 05. 03.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양한 지 두 달이 지났는데 아이가 정말 건강합니다. 브리더님의 철저한 건강 관리 덕분이에요.",
    reviewDate: "2024. 05. 15.",
  },
  {
    breederId: "14",
    breederName: "멍 7번째",
    breederLevel: "new",
    applicationDate: "2024. 05. 10.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담에서 모든 질문에 대해 친절하게 답변해주셔서 입양에 대한 확신을 갖게 되었습니다.",
    reviewDate: "2024. 05. 14.",
  },
  {
    breederId: "15",
    breederName: "냥 8번째",
    breederLevel: "elite",
    applicationDate: "2024. 05. 18.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양 후 아이가 가족과 잘 어울려 지내고 있습니다. 브리더님의 교육이 잘 되어있었어요.",
    reviewDate: "2024. 05. 28.",
  },
  {
    breederId: "16",
    breederName: "멍 8번째",
    breederLevel: "new",
    applicationDate: "2024. 05. 22.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담 시 브리더님의 전문성과 열정이 느껴졌습니다. 입양을 결정하는데 큰 도움이 되었어요.",
    reviewDate: "2024. 05. 26.",
  },
  {
    breederId: "17",
    breederName: "냥 9번째",
    breederLevel: "elite",
    applicationDate: "2024. 06. 01.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양 후 지금까지 아이가 건강하게 잘 지내고 있습니다. 브리더님의 세심한 케어가 인상적이었어요.",
    reviewDate: "2024. 06. 10.",
  },
  {
    breederId: "18",
    breederName: "멍 9번째",
    breederLevel: "new",
    applicationDate: "2024. 06. 08.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담에서 브리더님의 진심이 전해졌습니다. 입양에 대한 모든 정보를 투명하게 공유해주셔서 신뢰할 수 있었어요.",
    reviewDate: "2024. 06. 12.",
  },
  {
    breederId: "19",
    breederName: "냥 10번째",
    breederLevel: "elite",
    applicationDate: "2024. 06. 15.",
    profileImage: "/avatar-sample.png",
    animalType: "cat",
    reviewType: "입양 후기",
    reviewContent:
      "입양한 지 세 달이 지났는데 아이가 정말 건강하고 활발합니다. 브리더님의 케어가 탁월했습니다.",
    reviewDate: "2024. 06. 25.",
  },
  {
    breederId: "20",
    breederName: "멍 10번째",
    breederLevel: "new",
    applicationDate: "2024. 06. 20.",
    profileImage: "/avatar-sample.png",
    animalType: "dog",
    reviewType: "상담 후기",
    reviewContent:
      "상담 과정이 매우 체계적이고 전문적이었습니다. 브리더님의 노하우가 느껴져서 입양을 결정하게 되었어요.",
    reviewDate: "2024. 06. 24.",
  },
];
