export interface HomeAnimalData {
  id: string;
  avatarUrl: string;
  name: string;
  sex: "male" | "female";
  birth: string;
  price: string;
  breed: string;
  status: "available" | "reserved" | "completed";
}

export const homeAnimalMockData: HomeAnimalData[] = [
  {
    id: "1",
    avatarUrl: "/main-img-sample.png",
    name: "루시",
    sex: "female",
    birth: "2024년 01월 15일 생",
    price: "1,000,000원",
    breed: "메인쿤",
    status: "available",
  },
  {
    id: "2",
    avatarUrl: "/main-img-sample.png",
    name: "코코",
    sex: "male",
    birth: "2024년 02월 20일 생",
    price: "1,200,000원",
    breed: "러시안 블루",
    status: "available",
  },
  {
    id: "3",
    avatarUrl: "/main-img-sample.png",
    name: "미미",
    sex: "female",
    birth: "2024년 03월 10일 생",
    price: "900,000원",
    breed: "샴",
    status: "available",
  },
  {
    id: "4",
    avatarUrl: "/main-img-sample.png",
    name: "토토",
    sex: "male",
    birth: "2024년 01월 25일 생",
    price: "1,100,000원",
    breed: "메인쿤",
    status: "available",
  },
  {
    id: "5",
    avatarUrl: "/main-img-sample.png",
    name: "나비",
    sex: "female",
    birth: "2024년 02월 05일 생",
    price: "950,000원",
    breed: "페르시안",
    status: "available",
  },
  {
    id: "6",
    avatarUrl: "/main-img-sample.png",
    name: "초코",
    sex: "male",
    birth: "2024년 03월 15일 생",
    price: "1,300,000원",
    breed: "브리티쉬 쇼트헤어",
    status: "available",
  },
  {
    id: "7",
    avatarUrl: "/main-img-sample.png",
    name: "별이",
    sex: "female",
    birth: "2024년 01월 30일 생",
    price: "1,050,000원",
    breed: "노르웨이 숲",
    status: "available",
  },
  {
    id: "8",
    avatarUrl: "/main-img-sample.png",
    name: "모모",
    sex: "male",
    birth: "2024년 02월 12일 생",
    price: "1,150,000원",
    breed: "스코티시 폴드",
    status: "available",
  },
  {
    id: "9",
    avatarUrl: "/main-img-sample.png",
    name: "하니",
    sex: "female",
    birth: "2024년 03월 20일 생",
    price: "1,000,000원",
    breed: "아메리칸 쇼트헤어",
    status: "available",
  },
  {
    id: "10",
    avatarUrl: "/main-img-sample.png",
    name: "뽀삐",
    sex: "male",
    birth: "2024년 01월 08일 생",
    price: "1,250,000원",
    breed: "벵갈",
    status: "available",
  },
  {
    id: "11",
    avatarUrl: "/main-img-sample.png",
    name: "라라",
    sex: "female",
    birth: "2024년 02월 28일 생",
    price: "1,150,000원",
    breed: "코리안 숏헤어",
    status: "available",
  },
  {
    id: "12",
    avatarUrl: "/main-img-sample.png",
    name: "구름",
    sex: "male",
    birth: "2024년 03월 05일 생",
    price: "1,050,000원",
    breed: "샴",
    status: "available",
  },
  {
    id: "13",
    avatarUrl: "/main-img-sample.png",
    name: "초롱",
    sex: "female",
    birth: "2024년 01월 18일 생",
    price: "1,200,000원",
    breed: "먼치킨",
    status: "available",
  },
  {
    id: "14",
    avatarUrl: "/main-img-sample.png",
    name: "두리",
    sex: "male",
    birth: "2024년 02월 08일 생",
    price: "1,180,000원",
    breed: "스핑크스",
    status: "available",
  },
  {
    id: "15",
    avatarUrl: "/main-img-sample.png",
    name: "미로",
    sex: "female",
    birth: "2024년 03월 22일 생",
    price: "1,300,000원",
    breed: "노르웨이 숲",
    status: "available",
  },
  {
    id: "16",
    avatarUrl: "/main-img-sample.png",
    name: "밤비",
    sex: "male",
    birth: "2024년 01월 12일 생",
    price: "1,100,000원",
    breed: "브리티쉬 쇼트헤어",
    status: "available",
  },
  {
    id: "17",
    avatarUrl: "/main-img-sample.png",
    name: "스텔라",
    sex: "female",
    birth: "2024년 02월 02일 생",
    price: "1,250,000원",
    breed: "러시안 블루",
    status: "available",
  },
  {
    id: "18",
    avatarUrl: "/main-img-sample.png",
    name: "토리",
    sex: "male",
    birth: "2024년 03월 08일 생",
    price: "1,050,000원",
    breed: "메인쿤",
    status: "available",
  },
];
