import Container from "@/components/ui/container";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const pretendard = localFont({
  src: "../assets/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable}  ${pretendard.className}`}
    >
      <body
        className={`${pretendard.variable}  ${pretendard.className} antialiased`}
      >
        <Container>{children}</Container>
      </body>
    </html>
  );
}
